title: WithY
email: withYao@outlook.com
description: Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username: withY-proto

# Build settings
theme: minima
plugins:
  - jekyll-feed

